#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("ScheduleApp.Droid.Resource", IsApplication=true)]

namespace ScheduleApp.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Forms.Platform.Resource.String.ApplicationName = global::ScheduleApp.Droid.Resource.String.ApplicationName;
			global::Xamarin.Forms.Platform.Resource.String.Hello = global::ScheduleApp.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int monoandroidsplash = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060006
			public const int AddFrequency = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int AddFrequencyField = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int AddFrequencyUnitField = 2131099657;
			
			// aapt resource value: 0x7f06000b
			public const int CreateTask = 2131099659;
			
			// aapt resource value: 0x7f060008
			public const int addFrequencyUnit = 2131099656;
			
			// aapt resource value: 0x7f060004
			public const int addReminderEndDate = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int addReminderEndDateField = 2131099653;
			
			// aapt resource value: 0x7f060000
			public const int addTaskName = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int addTaskNameField = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int addTaskNotes = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int addTaskNotesField = 2131099651;
			
			// aapt resource value: 0x7f06000a
			public const int editText1 = 2131099658;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int NotNeededAddTask = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int NotNeededMain = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int NotNeededTaskViewer = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Mono_Android_Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
